# Generated by Django 3.2 on 2025-12-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Concepto')),
                ('monto', models.IntegerField(verbose_name='Monto (CLP)')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], default='gasto', max_length=10)),
                ('categoria', models.CharField(choices=[('ahorro', 'Ahorro / Inversión'), ('arriendo', 'Arriendo / Casa'), ('comida', 'Comida / Supermercado'), ('transporte', 'Transporte / Bencina'), ('deudas', 'Deudas / Préstamos'), ('ocio', 'Ocio / Entretenimiento'), ('salud', 'Salud / Farmacia'), ('varios', 'Varios / Otros'), ('sueldo', 'Sueldo / Honorarios')], default='varios', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('debito', 'Tarjeta Débito'), ('credito', 'Tarjeta Crédito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='debito', max_length=20)),
                ('tipo_gasto', models.CharField(choices=[('fijo', 'Gasto Fijo (Obligatorio)'), ('variable', 'Gasto Variable (Necesario)'), ('hormiga', 'Gasto Hormiga (Evitable)'), ('na', 'No Aplica (Ingresos)')], default='variable', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
            ],
        ),
    ]
