# Generated by Django 3.2 on 2025-12-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('sueldo', 'Sueldo'), ('negocio', 'Negocio'), ('mesada_tatas', 'Mesada Tatas'), ('mesada_luis', 'Mesada Tío Luis'), ('otro_ingreso', 'Otro Ingreso'), ('bencina', 'Bencina'), ('diezmo', 'Diezmo'), ('pasajes', 'Pasajes'), ('regalos', 'Regalos / Novia'), ('comida', 'Comida / Supermercado'), ('inversion', 'Inversión'), ('ahorro', 'Ahorro'), ('arriendo', 'Arriendo / Casa'), ('servicios', 'Cuentas (Luz/Agua)'), ('salud', 'Salud / Farmacia'), ('ocio', 'Ocio / Salidas'), ('varios', 'Varios / Otros')], default='varios', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso 🤑'), ('gasto', 'Gasto 💸')], default='gasto', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_gasto',
            field=models.CharField(choices=[('fijo', 'Gasto Fijo (Obligatorio)'), ('variable', 'Gasto Variable (Necesario)'), ('hormiga', 'Gasto Hormiga (Evitable)'), ('inversion', 'Inversión / Ahorro'), ('na', 'No Aplica (Ingresos)')], default='variable', max_length=20),
        ),
    ]
