# Generated by Django 3.2 on 2025-12-15 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0002_auto_20251215_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('sueldo', 'Sueldo'), ('negocio', 'Negocio'), ('mesada_tatas', 'Mesada Tatas'), ('mesada_luis', 'Mesada Tío Luis'), ('retorno_inversion', 'Retiro desde Ahorros 🏦'), ('otro_ingreso', 'Otro Ingreso'), ('bencina', 'Bencina'), ('diezmo', 'Diezmo'), ('pasajes', 'Pasajes'), ('regalos', 'Regalos / Novia'), ('comida', 'Comida / Supermercado'), ('inversion', 'Inversión 📈'), ('ahorro', 'Ahorro 🐖'), ('arriendo', 'Arriendo / Casa'), ('servicios', 'Cuentas (Luz/Agua)'), ('salud', 'Salud / Farmacia'), ('ocio', 'Ocio / Salidas'), ('varios', 'Varios / Otros')], default='varios', max_length=20),
        ),
    ]
