# Generated by Django 3.2 on 2025-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_auto_20251215_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('sueldo', 'Sueldo'), ('negocio', 'Negocio'), ('mesada_tatas', 'Mesada Tatas'), ('mesada_luis', 'Mesada Tío Luis'), ('retorno_ahorro', 'Retiro de Ahorros 🐖'), ('retorno_inversion', 'Retiro de Inversión 📈'), ('otro_ingreso', 'Otro Ingreso'), ('bencina', 'Bencina'), ('diezmo', 'Diezmo'), ('pasajes', 'Pasajes'), ('regalos', 'Regalos / Novia'), ('comida', 'Comida / Supermercado'), ('inversion', 'Inversión 📈'), ('ahorro', 'Ahorro 🐖'), ('arriendo', 'Arriendo / Casa'), ('servicios', 'Cuentas (Luz/Agua)'), ('salud', 'Salud / Farmacia'), ('ocio', 'Ocio / Salidas'), ('varios', 'Varios / Otros')], default='varios', max_length=20),
        ),
    ]
