# Generated by Django 3.2 on 2025-12-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_transaccion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuenta',
            field=models.CharField(choices=[('efectivo', 'Efectivo (Billetera)'), ('banco_estado', 'Banco Estado'), ('banco_falabella', 'Banco Falabella'), ('santander', 'Santander'), ('mach', 'MACH')], default='efectivo', max_length=50, verbose_name='¿Dónde se guarda/saca el dinero?'),
        ),
    ]
