# Generated by Django 3.2 on 2025-12-23 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0005_transaccion_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('sueldo', 'Sueldo'), ('negocio', 'Negocio'), ('mesada_tatas', 'Mesada Tatas'), ('mesada_luis', 'Mesada Tío Luis'), ('retorno_ahorro', 'Retiro de Ahorros 🐖'), ('retorno_inversion', 'Retiro de Inversión 📈'), ('perdida_inversion', 'Pérdida de Mercado 📉'), ('otro_ingreso', 'Otro Ingreso'), ('bencina', 'Bencina'), ('diezmo', 'Diezmo'), ('pasajes', 'Pasajes'), ('regalos', 'Regalos / Novia'), ('comida', 'Comida / Supermercado'), ('inversion', 'Inversión 📈'), ('ganancia_inversion', 'Ganancia de Mercado 📈'), ('ahorro', 'Ahorro 🐖'), ('arriendo', 'Arriendo / Casa'), ('servicios', 'Cuentas (Luz/Agua)'), ('salud', 'Salud / Farmacia'), ('ocio', 'Ocio / Salidas'), ('varios', 'Varios / Otros')], default='varios', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta',
            field=models.CharField(choices=[('efectivo', 'Efectivo (Billetera)'), ('banco_estado', 'Banco Estado'), ('banco_falabella', 'Banco Falabella'), ('santander', 'Santander'), ('mach', 'MACH'), ('Inversiones', 'Bóveda Inversiones')], default='efectivo', max_length=50, verbose_name='¿Dónde se guarda/saca el dinero?'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.CharField(choices=[('debito', 'Tarjeta Débito'), ('credito', 'Tarjeta Crédito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste Automático')], default='debito', max_length=20),
        ),
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Meta', max_length=50)),
                ('monto_objetivo', models.IntegerField(default=1000000)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
